defaults:
  seed: 0
  folds: 10
  load: True
  save: True
  use_ssh: True
  data_folder: ../datasets
  ckpt_folder: knowledge

groups:
  - cls98

results_folder: cls98/scarf-plus-ylinear

recipe:
  scarf-plus-ylinear:
    - module: tabzilla_preprocessor
    - module: numerical_standard_scaler
    - module: scarf_plus_ylinear_learner
      eta: 
        - 0.01
        - 0.03
      learner_args:
        - corruption_rate:
            - 0.1
            - 0.2
            - 0.4
        - None 
      encoder:
        - module: cat_tokenizer
          trainable: True
        - module: mlp_layer
          dims:
            - [256, 256]
            # - [256, 256, 256, 256]
            - [256, 128]
            - [256, 256, 128, 128]
          dropout: 
            - 0.0
            - 0.2
          residual: False
      svme: True
      std_coeff:
        # - 0.3
        - 1
        - 3
      cov_coeff:
        # - 0.3
        - 1
        - 3
      head: None
    - module: fit
      epochs: 200
      lr: 
        - 0.001
        - 0.0001
      wd: 0.00001
      optimizer: adamw
      scheduler: none
      batch_size: 256
      log_freq: 10
    - breakpoint: 1
    - module: transform
      batch_size: 256
    - module: standard_scaler
    - module: linear_model
      ridge:
        - 1.0
        - 0.01
        - 0.0001
    - module: eval
