defaults:
  seed: 0
  folds: 10
  load: True
  save: True
  use_ssh: True
  data_folder: ../datasets
  ckpt_folder: knowledge

groups:
  - cls98

results_folder: cls98/xgboost-embedding-ylinear

recipe:
  xgboost-embedding-ylinear:
    - module: tabzilla_preprocessor
    - module: numerical_standard_scaler
    - module: ylinear_learner

      encoder:
        - module: cat_tokenizer
          trainable: False
        - module: xgboost_embedding_layer
          eta:
            - 0.3
            - 0.2
            - 0.1
            - 0.05
          max_depth:
            - 5
            - 10
          num_boost_round:
            - 100
        - module: linear_layer
          output_dim: 
            - 32
            - 64

      svme: True
      std_coeff:
        - 1
        - 3
      cov_coeff:
        - 0.3
        - 1
        - 3
      head: None
    - module: fit
      epochs: 200
      lr: 
        # - 0.001
        - 0.005
      wd: 0.00001
      optimizer: adamw
      scheduler: none
      batch_size: 256
      log_freq: 10
    - breakpoint: 1
    - module: transform
      batch_size: 256
    - module: standard_scaler
    - module: linear_model
      ridge:
        - 1.0
        - 0.01
        - 0.0001
    - module: eval
