cls56:
  - "openml__Australian__146818"
  - "openml__LED-display-domain-7digit__125921"
  - "openml__MiceProtein__146800"
  - "openml__acute-inflammations__10089"
  - "openml__analcatdata_authorship__3549"
  - "openml__analcatdata_boxing1__3540"
  - "openml__analcatdata_chlamydia__3739"
  - "openml__analcatdata_dmft__3560"
  - "openml__anneal__2867"
  - "openml__autos__9"
  - "openml__balance-scale__11"
  - "openml__blood-transfusion-service-center__10101"
  - "openml__breast-cancer__145799"
  - "openml__breast-w__15"
  - "openml__colic__25"
  - "openml__colic__27"
  - "openml__credit-approval__29"
  - "openml__cylinder-bands__14954"
  - "openml__dermatology__35"
  - "openml__diabetes__37"
  - "openml__dresses-sales__125920"
  - "openml__ecoli__145977"
  - "openml__eucalyptus__2079"
  - "openml__fertility__9984"
  - "openml__fri_c0_100_5__3620"
  - "openml__fri_c3_100_5__3779"
  - "openml__glass__40"
  - "openml__hayes-roth__146063"
  - "openml__heart-c__48"
  - "openml__heart-h__50"
  - "openml__hill-valley__145847"
  - "openml__ilpd__9971"
  - "openml__ionosphere__145984"
  - "openml__iris__59"
  - "openml__irish__3543"
  - "openml__kc2__3913"
  - "openml__labor__4"
  - "openml__lung-cancer__146024"
  - "openml__lymph__10"
  - "openml__monks-problems-2__146065"
  - "openml__pc1__3918"
  - "openml__postoperative-patient-data__146210"
  - "openml__profb__3561"
  - "openml__qsar-biodeg__9957"
  - "openml__rabe_266__3647"
  - "openml__socmob__3797"
  - "openml__sonar__39"
  - "openml__synthetic_control__3512"
  - "openml__tae__47"
  - "openml__tic-tac-toe__49"
  - "openml__transplant__3748"
  - "openml__vehicle__53"
  - "openml__visualizing_environmental__3602"
  - "openml__visualizing_livestock__3731"
  - "openml__wdbc__9946"
  - "openml__yeast__145793"

cls98:
  - openml__Australian__146818
  - openml__Click_prediction_small__190408
  - openml__LED-display-domain-7digit__125921
  - openml__MiceProtein__146800
  - openml__PhishingWebsites__14952
  - openml__Satellite__167211
  - openml__SpeedDating__146607
  - openml__acute-inflammations__10089
  - openml__ada_agnostic__3896
  - openml__adult-census__3953
  - openml__analcatdata_authorship__3549
  - openml__analcatdata_boxing1__3540
  - openml__analcatdata_chlamydia__3739
  - openml__analcatdata_dmft__3560
  - openml__anneal__2867
  - openml__autos__9
  - openml__balance-scale__11
  - openml__bank-marketing__14965
  - openml__banknote-authentication__10093
  - openml__blood-transfusion-service-center__10101
  - openml__breast-cancer__145799
  - openml__breast-w__15
  - openml__car-evaluation__146192
  - openml__car__146821
  - openml__cardiotocography__9979
  - openml__churn__167141
  - openml__cjs__14967
  - openml__cmc__23
  - openml__colic__25
  - openml__colic__27
  - openml__credit-approval__29
  - openml__cylinder-bands__14954
  - openml__dermatology__35
  - openml__diabetes__37
  - openml__dna__167140
  - openml__dresses-sales__125920
  - openml__ecoli__145977
  - openml__elevators__3711
  - openml__eucalyptus__2079
  - openml__fertility__9984
  - openml__fri_c0_100_5__3620
  - openml__fri_c3_100_5__3779
  - openml__glass__40
  - openml__hayes-roth__146063
  - openml__heart-c__48
  - openml__heart-h__50
  - openml__hill-valley__145847
  - openml__ilpd__9971
  - openml__ionosphere__145984
  - openml__iris__59
  - openml__irish__3543
  - openml__jasmine__168911
  - openml__jm1__3904
  - openml__kc1__3917
  - openml__kc2__3913
  - openml__kr-vs-kp__3
  - openml__labor__4
  - openml__libras__360948
  - openml__lung-cancer__146024
  - openml__lymph__10
  - openml__mfeat-factors__12
  - openml__mfeat-fourier__14
  - openml__mfeat-karhunen__16
  - openml__mfeat-morphological__18
  - openml__mfeat-zernike__22
  - openml__monks-problems-2__146065
  - openml__mushroom__24
  - openml__musk__3950
  - openml__ozone-level-8hr__9978
  - openml__page-blocks__30
  - openml__pc1__3918
  - openml__pc3__3903
  - openml__pc4__3902
  - openml__phoneme__9952
  - openml__postoperative-patient-data__146210
  - openml__profb__3561
  - openml__qsar-biodeg__9957
  - openml__rabe_266__3647
  - openml__satimage__2074
  - openml__scene__3485
  - openml__semeion__9964
  - openml__sick__3021
  - openml__socmob__3797
  - openml__sonar__39
  - openml__spambase__43
  - openml__splice__45
  - openml__steel-plates-fault__146817
  - openml__synthetic_control__3512
  - openml__tae__47
  - openml__tic-tac-toe__49
  - openml__transplant__3748
  - openml__vehicle__53
  - openml__visualizing_environmental__3602
  - openml__visualizing_livestock__3731
  - openml__wall-robot-navigation__9960
  - openml__wdbc__9946
  - openml__wilt__146820
  - openml__yeast__145793

cls20:
  - "openml__SpeedDating__146607"
  - "openml__ada_agnostic__3896"
  - "openml__adult-census__3953"
  - "openml__bank-marketing__14965"
  - "openml__banknote-authentication__10093"
  - "openml__car__146821"
  - "openml__cardiotocography__9979"
  - "openml__cjs__14967"
  - "openml__cmc__23"
  - "openml__dna__167140"
  - "openml__elevators__3711"
  - "openml__kr-vs-kp__3"
  - "openml__phoneme__9952"
  - "openml__satimage__2074"
  - "openml__scene__3485"
  - "openml__semeion__9964"
  - "openml__sick__3021"
  - "openml__spambase__43"
  - "openml__splice__45"
  - "openml__wall-robot-navigation__9960"

cls42:
  - "openml__Click_prediction_small__190408"
  - "openml__PhishingWebsites__14952"
  - "openml__Satellite__167211"
  - "openml__SpeedDating__146607"
  - "openml__ada_agnostic__3896"
  - "openml__adult-census__3953"
  - "openml__bank-marketing__14965"
  - "openml__banknote-authentication__10093"
  - "openml__car-evaluation__146192"
  - "openml__car__146821"
  - "openml__cardiotocography__9979"
  - "openml__churn__167141"
  - "openml__cjs__14967"
  - "openml__cmc__23"
  - "openml__dna__167140"
  - "openml__elevators__3711"
  - "openml__jasmine__168911"
  - "openml__jm1__3904"
  - "openml__kc1__3917"
  - "openml__kr-vs-kp__3"
  - "openml__libras__360948"
  - "openml__mfeat-factors__12"
  - "openml__mfeat-fourier__14"
  - "openml__mfeat-karhunen__16"
  - "openml__mfeat-morphological__18"
  - "openml__mfeat-zernike__22"
  - "openml__mushroom__24"
  - "openml__musk__3950"
  - "openml__ozone-level-8hr__9978"
  - "openml__page-blocks__30"
  - "openml__pc3__3903"
  - "openml__pc4__3902"
  - "openml__phoneme__9952"
  - "openml__satimage__2074"
  - "openml__scene__3485"
  - "openml__semeion__9964"
  - "openml__sick__3021"
  - "openml__spambase__43"
  - "openml__splice__45"
  - "openml__steel-plates-fault__146817"
  - "openml__wall-robot-navigation__9960"
  - "openml__wilt__146820"

cls30:
  - "openml__credit-g__31"
  - "openml__monks-problems-2__146065"
  - "openml__kc1__3917"
  - "openml__qsar-biodeg__9957"
  - "openml__phoneme__9952"
  - "openml__ada_agnostic__3896"
  - "openml__electricity__219"
  - "openml__nomao__9977"
  - "openml__vehicle__53"
  - "openml__balance-scale__11"
  - "openml__mfeat-fourier__14"
  - "openml__SpeedDating__146607"
  - "openml__cnae-9__9981"
  - "openml__credit-approval__29"
  - "openml__splice__45"
  - "openml__mfeat-zernike__22"
  - "openml__GesturePhaseSegmentationProcessed__14969"
  - "openml__Bioresponse__9910"
  - "openml__higgs__146606"
  - "openml__profb__3561"
  - "openml__one-hundred-plants-texture__9956"
  - "openml__artificial-characters__14964"
  - "openml__jungle_chess_2pcs_raw_endgame_complete__167119"
  - "openml__audiology__7"
  - "openml__Australian__146818"
  - "openml__socmob__3797"
  - "openml__elevators__3711"
  - "openml__lymph__10"
  - "openml__heart-h__50"
  - "openml__colic__25"

cls36:
  - "openml__credit-g__31"
  - "openml__monks-problems-2__146065"
  - "openml__kc1__3917"
  - "openml__qsar-biodeg__9957"
  - "openml__phoneme__9952"
  - "openml__ada_agnostic__3896"
  - "openml__electricity__219"
  - "openml__nomao__9977"
  - "openml__vehicle__53"
  - "openml__balance-scale__11"
  - "openml__mfeat-fourier__14"
  - "openml__SpeedDating__146607"
  - "openml__cnae-9__9981"
  - "openml__credit-approval__29"
  - "openml__splice__45"
  - "openml__mfeat-zernike__22"
  - "openml__GesturePhaseSegmentationProcessed__14969"
  - "openml__Bioresponse__9910"
  - "openml__higgs__146606"
  - "openml__profb__3561"
  - "openml__one-hundred-plants-texture__9956"
  - "openml__artificial-characters__14964"
  - "openml__jungle_chess_2pcs_raw_endgame_complete__167119"
  - "openml__audiology__7"
  - "openml__Australian__146818"
  - "openml__socmob__3797"
  - "openml__elevators__3711"
  - "openml__lymph__10"
  - "openml__heart-h__50"
  - "openml__colic__25"
  - "openml__MiniBooNE__168335"
  - "openml__guillermo__168337"
  - "openml__airlines__189354"
  - "openml__jasmine__168911"
  - "openml__poker-hand__9890"
  - "openml__albert__189356"

reg:
  - "openml__Bank-Note-Authentication-UCI__361002"
  # - "openml__EgyptianSkulls__5040"
  - "openml__Moneyball__361616"
  - "openml__Wine__190420"
  - "openml__Wisconsin-breast-cancer-cytology-features__361003"
  - "openml__abalone__361234"
  - "openml__airfoil_self_noise__361235"
  - "openml__aloi__12732"
  - "openml__auction_verification__361236"
  - "openml__bodyfat__5514"
  - "openml__brazilian_houses__361267"
  - "openml__california__361089"
  - "openml__california_housing__361255"
  # - "openml__chscase_foot__5012"
  - "openml__cleveland__2285"
  - "openml__colleges__359942"
  - "openml__concrete_compressive_strength__361237"
  - "openml__cps88wages__361261"
  - "openml__cpu_activity__361256"
  - "openml__cpu_small__4883"
  - "openml__dataset_sales__190418"
  - "openml__diamonds__361257"
  - "openml__fifa__361272"
  # - "openml__geographical_origin_of_music__361243"
  - "openml__grid_stability__361251"
  - "openml__health_insurance__361269"
  - "openml__kin8nm__2280"
  - "openml__kin8nm__361258"
  - "openml__kings_county__361266"
  # - "openml__liver-disorders__52948"
  # - "openml__meta__4729"
  - "openml__miami_housing__361260"
  - "openml__mv__4774"
  - "openml__naval_propulsion_plant__361247"
  - "openml__pbc__4850"
  - "openml__physiochemical_protein__361241"
  - "openml__pumadyn32nh__361259"
  - "openml__red_wine__361250"
  - "openml__sarcos__361254"
  - "openml__socmob__361264"
  # - "openml__solar_flare__361244"
  # - "openml__sulfur__360966"
  # - "openml__superconductivity__361242"
  # - "openml__veteran__4828"
  - "openml__video_transcoding__361252"
  - "openml__white_wine__361249"
  

reg_small:
  - "openml__Bank-Note-Authentication-UCI__361002"
  - "openml__Moneyball__361616"
  - "openml__Wine__190420"
  - "openml__Wisconsin-breast-cancer-cytology-features__361003"
  - "openml__abalone__361234"
  - "openml__airfoil_self_noise__361235"
  - "openml__auction_verification__361236"
  # - "openml__bodyfat__5514"
  # - "openml__cleveland__2285"
  - "openml__colleges__359942"
  - "openml__concrete_compressive_strength__361237"
  - "openml__cpu_activity__361256"
  - "openml__dataset_sales__190418"
  - "openml__fifa__361272"
  # - "openml__kin8nm__2280"
  - "openml__kin8nm__361258"
  - "openml__kings_county__361266"
  - "openml__naval_propulsion_plant__361247"
  # - "openml__pbc__4850"
  - "openml__pumadyn32nh__361259"
  - "openml__red_wine__361250"
  - "openml__socmob__361264"
  - "openml__white_wine__361249"


reg_large:
  - "openml__brazilian_houses__361267"
  - "openml__california__361089"
  - "openml__california_housing__361255"
  - "openml__cps88wages__361261"
  - "openml__cpu_small__4883"
  - "openml__grid_stability__361251"
  - "openml__health_insurance__361269"
  - "openml__miami_housing__361260"
  - "openml__mv__4774"
  - "openml__physiochemical_protein__361241"
  - "openml__sarcos__361254"


reg_huge:
  - "openml__aloi__12732"
  - "openml__diamonds__361257"
  - "openml__video_transcoding__361252"
  

reg20:
  - "openml__Bank-Note-Authentication-UCI__361002"
  - "openml__Moneyball__361616"
  - "openml__Wine__190420"
  - "openml__Wisconsin-breast-cancer-cytology-features__361003"
  - "openml__abalone__361234"
  - "openml__airfoil_self_noise__361235"
  - "openml__auction_verification__361236"
  - "openml__california_housing__361255"
  - "openml__colleges__359942"
  - "openml__concrete_compressive_strength__361237"
  - "openml__cpu_activity__361256"
  - "openml__dataset_sales__190418"
  - "openml__fifa__361272"
  - "openml__grid_stability__361251"
  - "openml__health_insurance__361269"
  - "openml__kin8nm__361258"
  - "openml__kings_county__361266"
  - "openml__naval_propulsion_plant__361247"
  - "openml__pumadyn32nh__361259"
  - "openml__socmob__361264"

reg10:
  - "openml__Moneyball__361616"
  - "openml__Wine__190420"
  - "openml__abalone__361234"
  - "openml__airfoil_self_noise__361235"
  - "openml__california_housing__361255"
  - "openml__colleges__359942"
  - "openml__fifa__361272"
  - "openml__grid_stability__361251"
  - "openml__health_insurance__361269"
  - "openml__kings_county__361266"
