ad47:
  - "1_ad_ALOI"
  - "2_ad_annthyroid"
  - "3_ad_backdoor"
  - "4_ad_breastw"
  - "5_ad_campaign"
  - "6_ad_cardio"
  - "7_ad_Cardiotocography"
  - "8_ad_celeba"
  - "9_ad_census"
  - "10_ad_cover"
  - "11_ad_donors"
  - "12_ad_fault"
  - "13_ad_fraud"
  - "14_ad_glass"
  - "15_ad_Hepatitis"
  - "16_ad_http"
  - "17_ad_InternetAds"
  - "18_ad_Ionosphere"
  - "19_ad_landsat"
  - "20_ad_letter"
  - "21_ad_Lymphography"
  - "22_ad_magic"
  - "23_ad_mammography"
  - "24_ad_mnist"
  - "25_ad_musk"
  - "26_ad_optdigits"
  - "27_ad_PageBlocks"
  - "28_ad_pendigits"
  - "29_ad_Pima"
  - "30_ad_satellite"
  - "31_ad_satimage-2"
  - "32_ad_shuttle"
  - "33_ad_skin"
  - "34_ad_smtp"
  - "35_ad_SpamBase"
  - "36_ad_speech"
  - "37_ad_Stamps"
  - "38_ad_thyroid"
  - "39_ad_vertebral"
  - "40_ad_vowels"
  - "41_ad_Waveform"
  - "42_ad_WBC"
  - "43_ad_WDBC"
  - "44_ad_Wilt"
  - "45_ad_wine"
  - "46_ad_WPBC"
  - "47_ad_yeast"

ad39:
  - "2_ad_annthyroid"
  - "3_ad_backdoor"
  - "4_ad_breastw"
  - "5_ad_campaign"
  - "6_ad_cardio"
  - "7_ad_Cardiotocography"
  - "9_ad_census"
  - "10_ad_cover"
  - "11_ad_donors"
  - "12_ad_fault"
  - "13_ad_fraud"
  - "14_ad_glass"
  - "15_ad_Hepatitis"
  - "16_ad_http"
  - "18_ad_Ionosphere"
  - "19_ad_landsat"
  - "21_ad_Lymphography"
  - "22_ad_magic"
  - "23_ad_mammography"
  - "25_ad_musk"
  - "27_ad_PageBlocks"
  - "29_ad_Pima"
  - "30_ad_satellite"
  - "31_ad_satimage-2"
  - "32_ad_shuttle"
  - "34_ad_smtp"
  - "35_ad_SpamBase"
  - "36_ad_speech"
  - "37_ad_Stamps"
  - "38_ad_thyroid"
  - "39_ad_vertebral"
  - "40_ad_vowels"
  - "41_ad_Waveform"
  - "42_ad_WBC"
  - "43_ad_WDBC"
  - "44_ad_Wilt"
  - "45_ad_wine"
  - "46_ad_WPBC"
  - "47_ad_yeast"
