defaults:
  data_folder: anomaly/anomaly_data_truncated
  seed: 0
  epochs: 2000
  folds: 5
  log_interval: 10
  weight_decay: 0.00001
  scale_numerical_features: MinMax
  ckpt_folder: ../ckpt
  result_file: ../results_debug/result.csv

groups:
  - ad47
#datasets:
#  - "2_annthyroid"


recipe:
  lof/recipe 1:
    - module: anomaly_preprocessor
#    - module: numerical_standard_scaler
#    - module: standard_scaler
#    - module: pyod_lof
#      n_neighbors: 30
#      contamination: 0.1
    - module: pyod_iforest
      n_estimators: 100
      contamination: 0.1
      bootstrap: False
    - module: eval
